sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: MmGS/vm8b3skCykUjD2I44YYLvoIOc6gyRECPhMvbvZARzfaam+QOtwcbKcIVm8uP0GJKzjtcWRsE5/gdgGKeL3VAcQatFIWnb5pu8J8AIgV3EKjPQg5iyA8UR1Ca32uwlg1/O8/kFteRoac8M9mQEn0+MCbPWGKvE775N4KpOSlWLNgicD93LZH5UXrOOyFALFKTS7Ccqygh4nQfpuuNcpfYR8rLH/samYN/1u/ZhLdv1O97C8G9q5YIHRy4WN/z8iE4jXBXvTDBOP7kuM884XLcZE8i0N2nmNTOXF1XiJQKoTKpyrt8RM7fOeYHNborXbGcrY3jLUqH6bKSwmfhukLFNh3I6cQxrQd6bbX/hlxhYJuFWrbxUpKtmy/WLxOdJ3O/N3dCxH9U16T2JjzowSpaD4EkTPzZUO/QItYrEN4RBSdsXfYQh/jwkTSXCt7OZTz5gN3YB28OrA/n7BxTEWWiscL+xypbMplzYZVKAp0VAsBtZaQ8vT1UJPTIgycjFg6NHplz219rEFy6QZsgImPl3C8KXlijbPcu+O0hEQQwcCd/Zbr3M2fECYlrMi5UIaYjm8hjMraXxiSATdvZNbruPJP0e9P4XiDpfQvhIibEfCRO8szAH0qKRUqIyZ4bxbeONo4FVfcVu7cE1mEojyDwLaAkb1NecNsdjQnFeY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Stella-Fregelius--A-Tale-of-Three-Destinies_6051
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy